import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'
import App from './App'
import { Box, Container, Flex, Grid, GridItem } from '@chakra-ui/react'
import MyMap from '../components/MyMap'
import MyOrders from '../components/MyOrders'
import MyApp from './_app'
import MyTabs from '../components/MyTabs'
import Login from './Login'
import ThemeToggler from '../components/ThemeToggler'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Problem 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="row">
      <ThemeToggler />
        <Login />
      </Flex>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
